### ISSUE TITLE
Question : How you will trigger the test via maven for that sample? 

### ISSUE THREAD

**Issue by Romeh** [ktoso/akka-persistence-tck-testing-from-java#1]
Hey @ktoso  ,

Small question , how you can trigger the specs test via maven for your sample ?

Thanks a lot

**Comment by ktoso** [comment]
`mvn test` I guess?

Please note that this repo is not maintained and refers to an ages old version of Akka (not even 2.4 which is end of life in January but even 2.3 which is end of life since years).

**Comment by Romeh** [comment]
Thanks for reply , yes i use that already but i do not see any specific test cases being triggered , and in between i am using latest akka dependencies , i check their documentation and it says the same about maven dependencies and how to enable the journal specs but i do not see any test cases yet being triggered when i do mvn test

**Comment by ktoso** [comment]
Resolved by https://github.com/ktoso/akka-persistence-tck-testing-from-java/pull/2 please look at the example now.

I guess something must have changed in scalatest since the initial version of this repo (ages ago :))

**Comment by Romeh** [comment]
thx a lot it is clear to me how it is working , thanks again for your support 👍
